blurg/config/routes.rb
Rails.application.routes.draw do
  get 'sign_up' => 'users#new', as: :new_user
  post 'sign_up' => 'users#create', as: :users

  get 'sign_in' => 'session#new', as: :sign_in
  delete 'sign_out' => 'session#delete', as: :sign_out
  post "auth" => 'session#create', as: :auth

  get '/contact' => 'pages#contact', as: :contact

  get '/about' => 'pages#about', as: :about

  root 'pages#index'

end

blurg/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 15}

  belongs_to :user
end

blurg/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
  validates :username, presence: true, uniqueness: true
end

blurg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

blurg/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action do
    # get user from session[:user_id]
    # if we're not cool, redirect to sign_in
    @current_user = User.find_by id: session[:user_id]
    if @current_user.nil?
      redirect_to sign_in_path
    end
  end

  def contact
  end

  def about
  end

  def index
  end
end

blurg/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    username = params[:username]
    password = params[:password]

    # get the user
    user = User.find_by username: username
    # if user and auth is cool
    if (user) && (user.authenticate password)
      # set session
      session[:user_id] = user.id
      redirect_to root_path
    else
      # show page
      # let user know they stink
      flash.now[:alert] = "💩💩💩"
      render :new

    end
  end

  def delete
    session.delete :user_id
    redirect_to root_path, notice: "Ya logged out 😎"
  end
end

blurg/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "😎😎😎🎊™"
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:password, :password_confirmation)
  end
end

blurg/app/helpers/application_helper.rb
module ApplicationHelper
end

blurg/app/helpers/pages_helper.rb
module PagesHelper
end

blurg/app/helpers/session_helper.rb
module SessionHelper
end

blurg/app/helpers/users_helper.rb
module UsersHelper
end

blurg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blurg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<nav>
  <%= link_to "Home", root_path %>
  <%= link_to "About", about_path %>
  <%= link_to "Contact", contact_path %>

  <% if @current_user.present? %>
    Hi <%= @current_user.username %>.
    <%= link_to "Sign Out?", sign_out_path, method: :delete %>
  <% end %>

</nav>

<% if alert %>
  <div class="alert"><%= alert %></div>
<% end %>

<% if notice %>
  <div class="notice"><%= notice %></div>
<% end %>


<%= yield %>

</div>

</body>
</html>

blurg/app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

blurg/app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

blurg/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

blurg/app/views/session/new.html.erb
<h1>Sign in!</h1>

<%= form_tag auth_path, method: :post do %>
  <div class="form-group">
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:username], class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, "", class: "form-control"  %>
  </div>

  <div>
    <%= submit_tag "Sign in", class: "btn btn-primary" %> or <%= link_to "Sign Up", new_user_path %>
  </div>
<% end %>

blurg/app/views/users/new.html.erb
<h1>Welcome! Sign up!</h1>

<%= simple_form_for @user do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>